export const TYPOGRAPHY = {
  Heading28Bold: 'text-[28px] leading-[33px] not-italic font-bold', // line-height: 33px 체크 필요
  Heading124Bold:
    'text-2xl leading-[29px] tracking-[-0.96px] font-bold capitalize',
  Heading222Bold: 'text-xl leading-[29px] tracking-[-0.88px] font-bold',
  Heading222Semi: 'text-xl leading-[26px] tracking-[-0.88px] font-semibold',
  Heading222Medium: 'text-xl leading-[26px] tracking-[-0.88px] font-medium',
  Heading318Bold: 'text-lg leading-[21px] tracking-[-0.45px] font-bold',
  Heading318Semi: 'text-lg leading-[21px] tracking-[-0.72px] font-semibold',
  Heading318Medium: 'text-lg leading-[21px] tracking-[-0.45px] font-medium',
  Subheading16Bold: 'text-base leading-[20px] tracking-[-0.4px] font-bold',

  Subheading16Semi: 'text-base leading-[20px] tracking-[-0.4px] font-semibold',
  Subheading16Medium: 'text-base leading-[20px] tracking-[-0.4px] font-medium',
  Subheading16Regular: 'text-base leading-[20px] tracking-[-0.4px] font-normal',
  Body14Bold: 'text-sm leading-[20px] tracking-[-0.35px] font-bold',
  Body14Semi: 'text-sm leading-[20px] tracking-[-0.35px] font-semibold',
  Body14Medium: 'text-sm leading-[20px] tracking-[-0.35px] font-medium',
  Body14Regular: 'text-sm leading-[20px] tracking-[-0.35px] font-normal',
  Label12Bold: 'text-xs leading-[14px] tracking-[-0.3px] font-bold',
  Label12Semi: 'text-xs leading-[14px] tracking-[-0.3px] font-semibold',
  Label12Medium: 'text-xs leading-[14px] tracking-[-0.3px] font-medium',
  Label12Regular: 'text-xs leading-[14px] tracking-[-0.3px] font-normal',
  Caption11Medium: 'text-[11px] leading-[13px] tracking-[-0.275px] font-normal',
};

// {
//   Heading28Bold: 'text-[28px] not-italic font-bold leading-[32px]',
//   Heading124Bold:
//     'text-2xl leading-[24px] tracking-[-0.96px] font-bold capitalize',
//   Heading222Bold: 'text-xl leading-[22px] tracking-[-0.88px] font-bold',
//   Heading222Semi: 'text-xl leading-[22px] tracking-[-0.88px] font-semibold',
//   Heading222Medium: 'text-xl leading-[22px] tracking-[-0.88px] font-medium',
//   Heading318Bold: 'text-lg leading-[18px] tracking-[-0.45px] font-bold',
//   Heading318Semi: 'text-lg leading-[18px] tracking-[-0.72px] font-semibold',
//   Heading318Medium: 'text-lg leading-[18px] tracking-[-0.45px] font-medium',
//   Subheading16Bold: 'text-base leading-[20px] tracking-[-0.4px] font-bold',
//   Subheading16Semi: 'text-base leading-[20px] tracking-[-0.4px] font-semibold',
//   Subheading16Medium: 'text-base leading-[20px] tracking-[-0.4px] font-medium',
//   Subheading16Regular: 'text-base leading-[20px] tracking-[-0.4px] font-normal',
//   Body14Bold: 'text-sm leading-[20px] tracking-[-0.35px] font-bold',
//   Body14Semi: 'text-sm leading-[20px] tracking-[-0.35px] font-semibold',
//   Body14Medium: 'text-sm leading-[20px] tracking-[-0.35px] font-medium',
//   Body14Regular: 'text-sm leading-[20px] tracking-[-0.35px] font-normal',
//   Label12Bold: 'text-xs leading-[16px] tracking-[-0.3px] font-bold',
//   Label12Semi: 'text-xs leading-[16px] tracking-[-0.3px] font-semibold',
//   Label12Medium: 'text-xs leading-[16px] tracking-[-0.3px] font-medium',
//   Label12Regular: 'text-xs leading-[16px] tracking-[-0.3px] font-normal',
//   Caption11Medium: 'text-[11px] leading-[14px] tracking-[-0.275px] font-normal',
// };
